function ChannelInformationTableColumnFormat = FormatChannelInformationTableColumns(ModuleInfo)

% Bruel & Kjaer LAN-XI Open Application Programming Interface
% MATLAB Simple Recorder GUI Version 1.0 (September 15, 2021)
% By Matthew Houtteman and Gert Nyrup
% +1 800-332-2040
% TechnicalSalesSupport.US@hbkworld.com
% Developed in MATLAB R2021a with LAN-XI Firmware 2.10.0.501

% This function formats the columns of ChannelInformationTable

ChannelInformationTableColumnFormat = ({[] ...
    [] ...
    {'Yes' 'No'} ...
    transpose(ModuleInfo.supportedRanges) ...
    transpose(ModuleInfo.supportedFilters) ...
    {'Yes' 'No'} ...
    [] ...   
    {'Yes' 'No'} ...
    [] ...
    [] ...
    [] ...
    {'V/(m/s^2)' 'V/rad' 'V/(rad/s^2)' 'V/(rad/s)' 'V/C' 'V/A' 'V/m' 'V/J' 'V/N' 'V/Hz' 'V/kg' 'V/Nm' 'V/W' 'V/Pa' 'V/ohm' 'V/RPM' 'V/Pa' 'V/Pa' 'V/(m/m)' 'V/(N/m^2)' 'V/K' 'V/s' 'V/(m/s)' 'V/V' 'V/m^3' 'V/(m^3/s^2)' 'V/(m^3/s)'}});

end